DROP VIEW IF EXISTS dashboard_finanziaria CASCADE;
DROP VIEW IF EXISTS dashboard_cliente CASCADE;
DROP VIEW IF EXISTS view_finanziaries CASCADE;
DROP VIEW IF EXISTS report_finanziari CASCADE;

DROP TABLE IF EXISTS sottoscrizione CASCADE;
DROP TABLE IF EXISTS titolo CASCADE;
DROP TABLE IF EXISTS emittente CASCADE;
DROP TABLE IF EXISTS pagamento CASCADE;
DROP TABLE IF EXISTS pratica CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;