DROP TABLE IF EXISTS Sottoscrizione CASCADE;
DROP TABLE IF EXISTS Titolo CASCADE;
DROP TABLE IF EXISTS Emittente CASCADE;
DROP TABLE IF EXISTS Pagamento CASCADE;
DROP TABLE IF EXISTS Pratica CASCADE;
DROP TABLE IF EXISTS Cliente CASCADE;
